### ISSUE TITLE
confluence server support

### ISSUE THREAD

**Issue by lifesign** [BungaRazvan/confluence-link#25]
I have a locally deployed confluence server version 7.x, can you consider supporting synchronization?

**Comment by BungaRazvan** [comment]
hi. Could you expand a bit more on what you mean by synchronization?

**Comment by lifesign** [comment]
i mean upload mdfile to confluence server

**Comment by BungaRazvan** [comment]
sorry i dont quite understand what kind of authentication method you could elaborate more?

**Comment by BungaRazvan** [comment]
ok ... i will look into it.

**Comment by BungaRazvan** [comment]
I am sorry but I can't support it. every time I start my local confluence server It has a different problem
