### ISSUE TITLE
Bulleted lists not being upload properly

### ISSUE THREAD

**Issue by AutumnEvans418** [BungaRazvan/confluence-link#33]
When I upload the following notes:
![image](https://github.com/user-attachments/assets/c318f598-729d-4107-a517-761402798c17)

```markdown
# Architecture Types
- MVVM
	- Model, View, View Model
	- Mobile
	- Blazor
- MVC
	- Model View Controller
	- Web APIs
- 
```

I get this in confluence:
![image](https://github.com/user-attachments/assets/cb649a56-00eb-43f3-8664-380b3cbd16e3)

**Comment by BungaRazvan** [comment]
Greetings. Thank you for the report. I think I've solved the issue. Could you update the plugin and try again?

**Comment by AutumnEvans418** [comment]
Thanks for the quick response. That indeed fixed it. Thank you for building and sharing this. This is awesome.
